import { Outfit } from "next/font/google";
import "./globals.css";


const outfit = Outfit({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
  // se comento este apartado por que se buscara insertar distintas fuentes a futuro
  // variable: "--font-outfit"
});

export const metadata = {
  title: "Mi blog personal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${outfit.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
